#ifndef PEEKABOOLIB_GLOBAL_H
#define PEEKABOOLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PEEKABOOLIB_LIBRARY)
#  define PEEKABOOLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PEEKABOOLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PEEKABOOLIB_GLOBAL_H
